name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Install dependencies and build the project
      - name: Install Dependencies
        run: |
          npm install
          npm run build 

      # Step 3: Upload to S3 with MIME Types
      - name: Upload to S3 with MIME Types
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1 # Explicitly set the region
          VITE_APPWRITE_URL: ${{ secrets.VITE_APPWRITE_URL }}
          VITE_APPWRITE_PROJECT_ID: ${{ secrets.VITE_APPWRITE_PROJECT_ID }}
          VITE_APPWRITE_DATABASE_ID: ${{ secrets.VITE_APPWRITE_DATABASE_ID }}
          VITE_APPWRITE_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_COLLECTION_ID }}
          VITE_APPWRITE_BUCKET_ID: ${{ secrets.VITE_APPWRITE_BUCKET_ID }}
          VITE_TINYMCE_API_KEY: ${{ secrets.VITE_TINYMCE_API_KEY }}
        run: |
         
          aws s3 cp ./dist s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive \
            --region eu-north-1 \
            --exclude "*" --include "*.js" --content-type "application/javascript"

         
          aws s3 cp ./dist s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive \
            --region eu-north-1 \
            --exclude "*" --include "*.css" --content-type "text/css"

         
          aws s3 cp ./dist s3://${{ secrets.AWS_S3_BUCKET }}/ --recursive \
            --region eu-north-1 \
            --exclude "*" --include "*.html" --content-type "text/html"

      # Step 4: Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1 # Ensure the same region is used
          VITE_APPWRITE_URL: ${{ secrets.VITE_APPWRITE_URL }}
          VITE_APPWRITE_PROJECT_ID: ${{ secrets.VITE_APPWRITE_PROJECT_ID }}
          VITE_APPWRITE_DATABASE_ID: ${{ secrets.VITE_APPWRITE_DATABASE_ID }}
          VITE_APPWRITE_COLLECTION_ID: ${{ secrets.VITE_APPWRITE_COLLECTION_ID }}
          VITE_APPWRITE_BUCKET_ID: ${{ secrets.VITE_APPWRITE_BUCKET_ID }}
          VITE_TINYMCE_API_KEY: ${{ secrets.VITE_TINYMCE_API_KEY }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
